/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppBarangRouteImport } from './routes/_app/barang'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppLaporanRouteImport } from './routes/_app/laporan'
import { Route as AppPeminjamanRouteImport } from './routes/_app/peminjaman'
import { Route as AppPengaturanRouteImport } from './routes/_app/pengaturan'
import { Route as AppUangKeluarRouteImport } from './routes/_app/uang-keluar'
import { Route as AppUangMasukRouteImport } from './routes/_app/uang-masuk'
import { Route as AppPeminjamanIndexRouteImport } from './routes/_app/peminjaman.index'
import { Route as AppPeminjamanIdRouteImport } from './routes/_app/peminjaman.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBarangRoute = AppBarangRouteImport.update({
  id: '/barang',
  path: '/barang',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppPeminjamanRoute = AppPeminjamanRouteImport.update({
  id: '/peminjaman',
  path: '/peminjaman',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppUangKeluarRoute = AppUangKeluarRouteImport.update({
  id: '/uang-keluar',
  path: '/uang-keluar',
  getParentRoute: () => AppRoute,
} as any)
const AppUangMasukRoute = AppUangMasukRouteImport.update({
  id: '/uang-masuk',
  path: '/uang-masuk',
  getParentRoute: () => AppRoute,
} as any)
const AppPeminjamanIndexRoute = AppPeminjamanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeminjamanRoute,
} as any)
const AppPeminjamanIdRoute = AppPeminjamanIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPeminjamanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barang': typeof AppBarangRoute
  '/dashboard': typeof AppDashboardRoute
  '/laporan': typeof AppLaporanRoute
  '/peminjaman': typeof AppPeminjamanRouteWithChildren
  '/pengaturan': typeof AppPengaturanRoute
  '/uang-keluar': typeof AppUangKeluarRoute
  '/uang-masuk': typeof AppUangMasukRoute
  '/peminjaman/$id': typeof AppPeminjamanIdRoute
  '/peminjaman/': typeof AppPeminjamanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/barang': typeof AppBarangRoute
  '/dashboard': typeof AppDashboardRoute
  '/laporan': typeof AppLaporanRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/uang-keluar': typeof AppUangKeluarRoute
  '/uang-masuk': typeof AppUangMasukRoute
  '/peminjaman/$id': typeof AppPeminjamanIdRoute
  '/peminjaman': typeof AppPeminjamanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/barang': typeof AppBarangRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/peminjaman': typeof AppPeminjamanRouteWithChildren
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/uang-keluar': typeof AppUangKeluarRoute
  '/_app/uang-masuk': typeof AppUangMasukRoute
  '/_app/peminjaman/$id': typeof AppPeminjamanIdRoute
  '/_app/peminjaman/': typeof AppPeminjamanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/barang'
    | '/dashboard'
    | '/laporan'
    | '/peminjaman'
    | '/pengaturan'
    | '/uang-keluar'
    | '/uang-masuk'
    | '/peminjaman/$id'
    | '/peminjaman/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/barang'
    | '/dashboard'
    | '/laporan'
    | '/pengaturan'
    | '/uang-keluar'
    | '/uang-masuk'
    | '/peminjaman/$id'
    | '/peminjaman'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/barang'
    | '/_app/dashboard'
    | '/_app/laporan'
    | '/_app/peminjaman'
    | '/_app/pengaturan'
    | '/_app/uang-keluar'
    | '/_app/uang-masuk'
    | '/_app/peminjaman/$id'
    | '/_app/peminjaman/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/barang': {
      id: '/_app/barang'
      path: '/barang'
      fullPath: '/barang'
      preLoaderRoute: typeof AppBarangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/peminjaman': {
      id: '/_app/peminjaman'
      path: '/peminjaman'
      fullPath: '/peminjaman'
      preLoaderRoute: typeof AppPeminjamanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uang-keluar': {
      id: '/_app/uang-keluar'
      path: '/uang-keluar'
      fullPath: '/uang-keluar'
      preLoaderRoute: typeof AppUangKeluarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/uang-masuk': {
      id: '/_app/uang-masuk'
      path: '/uang-masuk'
      fullPath: '/uang-masuk'
      preLoaderRoute: typeof AppUangMasukRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/peminjaman/': {
      id: '/_app/peminjaman/'
      path: '/'
      fullPath: '/peminjaman/'
      preLoaderRoute: typeof AppPeminjamanIndexRouteImport
      parentRoute: typeof AppPeminjamanRoute
    }
    '/_app/peminjaman/$id': {
      id: '/_app/peminjaman/$id'
      path: '/$id'
      fullPath: '/peminjaman/$id'
      preLoaderRoute: typeof AppPeminjamanIdRouteImport
      parentRoute: typeof AppPeminjamanRoute
    }
  }
}

interface AppPeminjamanRouteChildren {
  AppPeminjamanIdRoute: typeof AppPeminjamanIdRoute
  AppPeminjamanIndexRoute: typeof AppPeminjamanIndexRoute
}

const AppPeminjamanRouteChildren: AppPeminjamanRouteChildren = {
  AppPeminjamanIdRoute: AppPeminjamanIdRoute,
  AppPeminjamanIndexRoute: AppPeminjamanIndexRoute,
}

const AppPeminjamanRouteWithChildren = AppPeminjamanRoute._addFileChildren(
  AppPeminjamanRouteChildren,
)

interface AppRouteChildren {
  AppBarangRoute: typeof AppBarangRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppPeminjamanRoute: typeof AppPeminjamanRouteWithChildren
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppUangKeluarRoute: typeof AppUangKeluarRoute
  AppUangMasukRoute: typeof AppUangMasukRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBarangRoute: AppBarangRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppPeminjamanRoute: AppPeminjamanRouteWithChildren,
  AppPengaturanRoute: AppPengaturanRoute,
  AppUangKeluarRoute: AppUangKeluarRoute,
  AppUangMasukRoute: AppUangMasukRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
